# model parameters
seq_len: 20
label_len: 48 #48

# model useless parameters
task_name: "classification"
pred_len: 0
num_class: 3
num_agents: 2
dropout: 0.1

# timesNet config
top_k: 3 #3
e_layers: 2 #2
d_layers: 1

enc_in: 10
c_out: 10
d_model: 128
embed: timeF
freq: d

num_kernels: 3
d_ff: 512


